name: Deploy MultiK8s
on:
  push:
    branches:
      - master

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin

      - name: Build
        run: |-
          docker build -t ${{ secrets.DOCKER_ID }}/multi-client -t ${{ secrets.DOCKER_ID }}/multi-client-k8s ./client/
          docker build -t ${{ secrets.DOCKER_ID }}/multi-server -t ${{ secrets.DOCKER_ID }}/multi-server-k8s ./server/
          docker build -t ${{ secrets.DOCKER_ID }}/multi-worker -t ${{ secrets.DOCKER_ID }}/multi-worker-k8s ./worker/
      - name: Push
        run: |-
          docker push ${{ secrets.DOCKER_ID }}/multi-client
          docker push ${{ secrets.DOCKER_ID }}/multi-server
          docker push ${{ secrets.DOCKER_ID }}/multi-worker
