name: Deploy MultiK8s
on:
  push:
    branches:
      - master

permissions:
  contents: 'read'
  id-token: 'write'

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin
          #docker build -f client/Dockerfile.dev -t ${{ secrets.DOCKER_ID }}/react-test .
          #docker run -e CI=true ${{ secrets.DOCKER_ID }}/react-test npm test

      - name: Set Service Key
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GKE_PROJECT_NAME }}

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_LOCATION }}

      - name: Build
        run: |-
          docker build -t ${{ secrets.DOCKER_ID }}/multi-client:latest -t ${{ secrets.DOCKER_ID }}/multi-client:${{ env.SHA }} ./client/
          docker build -t ${{ secrets.DOCKER_ID }}/multi-server:latest -t ${{ secrets.DOCKER_ID }}/multi-client:${{ env.SHA }} ./server/
          docker build -t ${{ secrets.DOCKER_ID }}/multi-worker:latest -t ${{ secrets.DOCKER_ID }}/multi-client:${{ env.SHA }} ./worker/

      - name: Push
        run: |-
          docker push ${{ secrets.DOCKER_ID }}/multi-client:latest
          docker push ${{ secrets.DOCKER_ID }}/multi-server:latest
          docker push ${{ secrets.DOCKER_ID }}/multi-worker:latest

          docker push ${{ secrets.DOCKER_ID }}/multi-client:${{ env.SHA }}
          docker push ${{ secrets.DOCKER_ID }}/multi-server:${{ env.SHA }}
          docker push ${{ secrets.DOCKER_ID }}/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f ./k8s/
          kubectl set image deployments/server-deployment server=${{ secrets.DOCKER_ID}}/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=${{ secrets.DOCKER_ID}}/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=${{ secrets.DOCKER_ID}}/multi-client:${{ env.SHA }}
